/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface EngagementMetrics {
  'shares' : bigint,
  'views' : bigint,
  'likes' : bigint,
  'comments' : bigint,
}
export type Platform = { 'x' : null } |
  { 'instagram' : null } |
  { 'googleTrends' : null } |
  { 'youtube' : null };
export interface Script {
  'duration' : bigint,
  'hookLine' : string,
  'language' : { 'hindi' : null } |
    { 'both' : null } |
    { 'english' : null },
  'style' : { 'dramatic' : null } |
    { 'emotional' : null },
  'mainContent' : string,
}
export type SubscriptionTier = { 'premium' : null } |
  { 'free' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface TrendingTopic {
  'id' : string,
  'topic' : string,
  'hashtags' : Array<string>,
  'metrics' : EngagementMetrics,
  'platform' : Platform,
  'keywords' : Array<string>,
  'timestamp' : bigint,
}
export interface UserAccount {
  'created' : bigint,
  'username' : string,
  'coins' : bigint,
  'tier' : SubscriptionTier,
  'videoHistory' : Array<string>,
}
export interface UserProfile {
  'username' : string,
  'name' : string,
  'tier' : SubscriptionTier,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoProject {
  'id' : string,
  'status' : VideoStatus,
  'title' : string,
  'created' : bigint,
  'voiceover' : { 'female' : null } |
    { 'male' : null },
  'owner' : Principal,
  'stockVideoIds' : Array<string>,
  'script' : Script,
  'watermark' : boolean,
  'subtitles' : boolean,
  'musicId' : string,
  'topicId' : string,
  'format' : { 'tiktok' : null } |
    { 'youtubeShorts' : null } |
    { 'instagramReels' : null },
}
export type VideoStatus = { 'completed' : null } |
  { 'rendering' : null } |
  { 'draft' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCoins' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTrendingTopic' : ActorMethod<
    [Platform, string, Array<string>, Array<string>],
    string
  >,
  'createUserAccount' : ActorMethod<[string], undefined>,
  'createVideoProject' : ActorMethod<
    [
      string,
      string,
      Script,
      Array<string>,
      string,
      { 'female' : null } |
        { 'male' : null },
      { 'tiktok' : null } |
        { 'youtubeShorts' : null } |
        { 'instagramReels' : null },
    ],
    string
  >,
  'deductCoins' : ActorMethod<[bigint], undefined>,
  'deleteTrendingTopic' : ActorMethod<[string], undefined>,
  'fetchTrendingTopicsFromGoogleTrendsApi' : ActorMethod<[], string>,
  'fetchTrendingTopicsFromYouTubeApi' : ActorMethod<[], string>,
  'filterTrendingTopicsByPlatform' : ActorMethod<
    [Platform],
    Array<TrendingTopic>
  >,
  'generateScript' : ActorMethod<
    [
      string,
      { 'hindi' : null } |
        { 'both' : null } |
        { 'english' : null },
      bigint,
      { 'dramatic' : null } |
        { 'emotional' : null },
    ],
    Script
  >,
  'getAccountByPrincipal' : ActorMethod<[Principal], [] | [UserAccount]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCallerVideoProjects' : ActorMethod<[], Array<VideoProject>>,
  'getTrendingTopic' : ActorMethod<[string], [] | [TrendingTopic]>,
  'getTrendingTopicsSortedByEngagement' : ActorMethod<[], Array<TrendingTopic>>,
  'getUserAccount' : ActorMethod<[], [] | [UserAccount]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideoProject' : ActorMethod<[string], [] | [VideoProject]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateTrendingTopic' : ActorMethod<
    [string, Platform, string, Array<string>, Array<string>, EngagementMetrics],
    undefined
  >,
  'updateVideoProject' : ActorMethod<
    [
      string,
      string,
      Array<string>,
      string,
      { 'female' : null } |
        { 'male' : null },
      boolean,
      { 'tiktok' : null } |
        { 'youtubeShorts' : null } |
        { 'instagramReels' : null },
      boolean,
    ],
    undefined
  >,
  'updateVideoProjectStatus' : ActorMethod<[string, VideoStatus], undefined>,
  'upgradeToPremium' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];