/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Platform = IDL.Variant({
  'x' : IDL.Null,
  'instagram' : IDL.Null,
  'googleTrends' : IDL.Null,
  'youtube' : IDL.Null,
});
export const Script = IDL.Record({
  'duration' : IDL.Nat,
  'hookLine' : IDL.Text,
  'language' : IDL.Variant({
    'hindi' : IDL.Null,
    'both' : IDL.Null,
    'english' : IDL.Null,
  }),
  'style' : IDL.Variant({ 'dramatic' : IDL.Null, 'emotional' : IDL.Null }),
  'mainContent' : IDL.Text,
});
export const EngagementMetrics = IDL.Record({
  'shares' : IDL.Nat,
  'views' : IDL.Nat,
  'likes' : IDL.Nat,
  'comments' : IDL.Nat,
});
export const TrendingTopic = IDL.Record({
  'id' : IDL.Text,
  'topic' : IDL.Text,
  'hashtags' : IDL.Vec(IDL.Text),
  'metrics' : EngagementMetrics,
  'platform' : Platform,
  'keywords' : IDL.Vec(IDL.Text),
  'timestamp' : IDL.Int,
});
export const SubscriptionTier = IDL.Variant({
  'premium' : IDL.Null,
  'free' : IDL.Null,
});
export const UserAccount = IDL.Record({
  'created' : IDL.Int,
  'username' : IDL.Text,
  'coins' : IDL.Nat,
  'tier' : SubscriptionTier,
  'videoHistory' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'name' : IDL.Text,
  'tier' : SubscriptionTier,
});
export const VideoStatus = IDL.Variant({
  'completed' : IDL.Null,
  'rendering' : IDL.Null,
  'draft' : IDL.Null,
});
export const VideoProject = IDL.Record({
  'id' : IDL.Text,
  'status' : VideoStatus,
  'title' : IDL.Text,
  'created' : IDL.Int,
  'voiceover' : IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null }),
  'owner' : IDL.Principal,
  'stockVideoIds' : IDL.Vec(IDL.Text),
  'script' : Script,
  'watermark' : IDL.Bool,
  'subtitles' : IDL.Bool,
  'musicId' : IDL.Text,
  'topicId' : IDL.Text,
  'format' : IDL.Variant({
    'tiktok' : IDL.Null,
    'youtubeShorts' : IDL.Null,
    'instagramReels' : IDL.Null,
  }),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCoins' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTrendingTopic' : IDL.Func(
      [Platform, IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'createUserAccount' : IDL.Func([IDL.Text], [], []),
  'createVideoProject' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Script,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null }),
        IDL.Variant({
          'tiktok' : IDL.Null,
          'youtubeShorts' : IDL.Null,
          'instagramReels' : IDL.Null,
        }),
      ],
      [IDL.Text],
      [],
    ),
  'deductCoins' : IDL.Func([IDL.Nat], [], []),
  'deleteTrendingTopic' : IDL.Func([IDL.Text], [], []),
  'fetchTrendingTopicsFromGoogleTrendsApi' : IDL.Func([], [IDL.Text], []),
  'fetchTrendingTopicsFromYouTubeApi' : IDL.Func([], [IDL.Text], []),
  'filterTrendingTopicsByPlatform' : IDL.Func(
      [Platform],
      [IDL.Vec(TrendingTopic)],
      ['query'],
    ),
  'generateScript' : IDL.Func(
      [
        IDL.Text,
        IDL.Variant({
          'hindi' : IDL.Null,
          'both' : IDL.Null,
          'english' : IDL.Null,
        }),
        IDL.Nat,
        IDL.Variant({ 'dramatic' : IDL.Null, 'emotional' : IDL.Null }),
      ],
      [Script],
      [],
    ),
  'getAccountByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserAccount)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerVideoProjects' : IDL.Func([], [IDL.Vec(VideoProject)], ['query']),
  'getTrendingTopic' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(TrendingTopic)],
      ['query'],
    ),
  'getTrendingTopicsSortedByEngagement' : IDL.Func(
      [],
      [IDL.Vec(TrendingTopic)],
      ['query'],
    ),
  'getUserAccount' : IDL.Func([], [IDL.Opt(UserAccount)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideoProject' : IDL.Func([IDL.Text], [IDL.Opt(VideoProject)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateTrendingTopic' : IDL.Func(
      [
        IDL.Text,
        Platform,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        EngagementMetrics,
      ],
      [],
      [],
    ),
  'updateVideoProject' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null }),
        IDL.Bool,
        IDL.Variant({
          'tiktok' : IDL.Null,
          'youtubeShorts' : IDL.Null,
          'instagramReels' : IDL.Null,
        }),
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateVideoProjectStatus' : IDL.Func([IDL.Text, VideoStatus], [], []),
  'upgradeToPremium' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Platform = IDL.Variant({
    'x' : IDL.Null,
    'instagram' : IDL.Null,
    'googleTrends' : IDL.Null,
    'youtube' : IDL.Null,
  });
  const Script = IDL.Record({
    'duration' : IDL.Nat,
    'hookLine' : IDL.Text,
    'language' : IDL.Variant({
      'hindi' : IDL.Null,
      'both' : IDL.Null,
      'english' : IDL.Null,
    }),
    'style' : IDL.Variant({ 'dramatic' : IDL.Null, 'emotional' : IDL.Null }),
    'mainContent' : IDL.Text,
  });
  const EngagementMetrics = IDL.Record({
    'shares' : IDL.Nat,
    'views' : IDL.Nat,
    'likes' : IDL.Nat,
    'comments' : IDL.Nat,
  });
  const TrendingTopic = IDL.Record({
    'id' : IDL.Text,
    'topic' : IDL.Text,
    'hashtags' : IDL.Vec(IDL.Text),
    'metrics' : EngagementMetrics,
    'platform' : Platform,
    'keywords' : IDL.Vec(IDL.Text),
    'timestamp' : IDL.Int,
  });
  const SubscriptionTier = IDL.Variant({
    'premium' : IDL.Null,
    'free' : IDL.Null,
  });
  const UserAccount = IDL.Record({
    'created' : IDL.Int,
    'username' : IDL.Text,
    'coins' : IDL.Nat,
    'tier' : SubscriptionTier,
    'videoHistory' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'name' : IDL.Text,
    'tier' : SubscriptionTier,
  });
  const VideoStatus = IDL.Variant({
    'completed' : IDL.Null,
    'rendering' : IDL.Null,
    'draft' : IDL.Null,
  });
  const VideoProject = IDL.Record({
    'id' : IDL.Text,
    'status' : VideoStatus,
    'title' : IDL.Text,
    'created' : IDL.Int,
    'voiceover' : IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null }),
    'owner' : IDL.Principal,
    'stockVideoIds' : IDL.Vec(IDL.Text),
    'script' : Script,
    'watermark' : IDL.Bool,
    'subtitles' : IDL.Bool,
    'musicId' : IDL.Text,
    'topicId' : IDL.Text,
    'format' : IDL.Variant({
      'tiktok' : IDL.Null,
      'youtubeShorts' : IDL.Null,
      'instagramReels' : IDL.Null,
    }),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCoins' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTrendingTopic' : IDL.Func(
        [Platform, IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'createUserAccount' : IDL.Func([IDL.Text], [], []),
    'createVideoProject' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Script,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null }),
          IDL.Variant({
            'tiktok' : IDL.Null,
            'youtubeShorts' : IDL.Null,
            'instagramReels' : IDL.Null,
          }),
        ],
        [IDL.Text],
        [],
      ),
    'deductCoins' : IDL.Func([IDL.Nat], [], []),
    'deleteTrendingTopic' : IDL.Func([IDL.Text], [], []),
    'fetchTrendingTopicsFromGoogleTrendsApi' : IDL.Func([], [IDL.Text], []),
    'fetchTrendingTopicsFromYouTubeApi' : IDL.Func([], [IDL.Text], []),
    'filterTrendingTopicsByPlatform' : IDL.Func(
        [Platform],
        [IDL.Vec(TrendingTopic)],
        ['query'],
      ),
    'generateScript' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({
            'hindi' : IDL.Null,
            'both' : IDL.Null,
            'english' : IDL.Null,
          }),
          IDL.Nat,
          IDL.Variant({ 'dramatic' : IDL.Null, 'emotional' : IDL.Null }),
        ],
        [Script],
        [],
      ),
    'getAccountByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserAccount)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerVideoProjects' : IDL.Func([], [IDL.Vec(VideoProject)], ['query']),
    'getTrendingTopic' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(TrendingTopic)],
        ['query'],
      ),
    'getTrendingTopicsSortedByEngagement' : IDL.Func(
        [],
        [IDL.Vec(TrendingTopic)],
        ['query'],
      ),
    'getUserAccount' : IDL.Func([], [IDL.Opt(UserAccount)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideoProject' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(VideoProject)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateTrendingTopic' : IDL.Func(
        [
          IDL.Text,
          Platform,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          EngagementMetrics,
        ],
        [],
        [],
      ),
    'updateVideoProject' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null }),
          IDL.Bool,
          IDL.Variant({
            'tiktok' : IDL.Null,
            'youtubeShorts' : IDL.Null,
            'instagramReels' : IDL.Null,
          }),
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateVideoProjectStatus' : IDL.Func([IDL.Text, VideoStatus], [], []),
    'upgradeToPremium' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };