/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface TrendingTopic {
    id: string;
    topic: string;
    hashtags: Array<string>;
    metrics: EngagementMetrics;
    platform: Platform;
    keywords: Array<string>;
    timestamp: bigint;
}
export interface UserAccount {
    created: bigint;
    username: string;
    coins: bigint;
    tier: SubscriptionTier;
    videoHistory: Array<string>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface EngagementMetrics {
    shares: bigint;
    views: bigint;
    likes: bigint;
    comments: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Script {
    duration: bigint;
    hookLine: string;
    language: Variant_hindi_both_english;
    style: Variant_dramatic_emotional;
    mainContent: string;
}
export interface VideoProject {
    id: string;
    status: VideoStatus;
    title: string;
    created: bigint;
    voiceover: Variant_female_male;
    owner: Principal;
    stockVideoIds: Array<string>;
    script: Script;
    watermark: boolean;
    subtitles: boolean;
    musicId: string;
    topicId: string;
    format: Variant_tiktok_youtubeShorts_instagramReels;
}
export interface UserProfile {
    username: string;
    name: string;
    tier: SubscriptionTier;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum Platform {
    x = "x",
    instagram = "instagram",
    googleTrends = "googleTrends",
    youtube = "youtube"
}
export enum SubscriptionTier {
    premium = "premium",
    free = "free"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_dramatic_emotional {
    dramatic = "dramatic",
    emotional = "emotional"
}
export enum Variant_female_male {
    female = "female",
    male = "male"
}
export enum Variant_hindi_both_english {
    hindi = "hindi",
    both = "both",
    english = "english"
}
export enum Variant_tiktok_youtubeShorts_instagramReels {
    tiktok = "tiktok",
    youtubeShorts = "youtubeShorts",
    instagramReels = "instagramReels"
}
export enum VideoStatus {
    completed = "completed",
    rendering = "rendering",
    draft = "draft"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCoins(amount: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createTrendingTopic(platform: Platform, topic: string, hashtags: Array<string>, keywords: Array<string>): Promise<string>;
    createUserAccount(username: string): Promise<void>;
    createVideoProject(title: string, topicId: string, script: Script, stockVideoIds: Array<string>, musicId: string, voiceover: Variant_female_male, format: Variant_tiktok_youtubeShorts_instagramReels): Promise<string>;
    deductCoins(amount: bigint): Promise<void>;
    deleteTrendingTopic(id: string): Promise<void>;
    fetchTrendingTopicsFromGoogleTrendsApi(): Promise<string>;
    fetchTrendingTopicsFromYouTubeApi(): Promise<string>;
    filterTrendingTopicsByPlatform(platform: Platform): Promise<Array<TrendingTopic>>;
    generateScript(topic: string, language: Variant_hindi_both_english, duration: bigint, style: Variant_dramatic_emotional): Promise<Script>;
    getAccountByPrincipal(user: Principal): Promise<UserAccount | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCallerVideoProjects(): Promise<Array<VideoProject>>;
    getTrendingTopic(id: string): Promise<TrendingTopic | null>;
    getTrendingTopicsSortedByEngagement(): Promise<Array<TrendingTopic>>;
    getUserAccount(): Promise<UserAccount | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVideoProject(id: string): Promise<VideoProject | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateTrendingTopic(id: string, platform: Platform, topic: string, hashtags: Array<string>, keywords: Array<string>, metrics: EngagementMetrics): Promise<void>;
    updateVideoProject(id: string, title: string, stockVideoIds: Array<string>, musicId: string, voiceover: Variant_female_male, subtitles: boolean, format: Variant_tiktok_youtubeShorts_instagramReels, watermark: boolean): Promise<void>;
    updateVideoProjectStatus(id: string, status: VideoStatus): Promise<void>;
    upgradeToPremium(): Promise<void>;
}
import type { EngagementMetrics as _EngagementMetrics, Platform as _Platform, Script as _Script, SubscriptionTier as _SubscriptionTier, TrendingTopic as _TrendingTopic, UserAccount as _UserAccount, UserProfile as _UserProfile, UserRole as _UserRole, VideoProject as _VideoProject, VideoStatus as _VideoStatus, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCoins(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCoins(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCoins(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createTrendingTopic(arg0: Platform, arg1: string, arg2: Array<string>, arg3: Array<string>): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createTrendingTopic(to_candid_Platform_n10(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTrendingTopic(to_candid_Platform_n10(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
            return result;
        }
    }
    async createUserAccount(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUserAccount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUserAccount(arg0);
            return result;
        }
    }
    async createVideoProject(arg0: string, arg1: string, arg2: Script, arg3: Array<string>, arg4: string, arg5: Variant_female_male, arg6: Variant_tiktok_youtubeShorts_instagramReels): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createVideoProject(arg0, arg1, to_candid_Script_n12(this._uploadFile, this._downloadFile, arg2), arg3, arg4, to_candid_variant_n16(this._uploadFile, this._downloadFile, arg5), to_candid_variant_n17(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVideoProject(arg0, arg1, to_candid_Script_n12(this._uploadFile, this._downloadFile, arg2), arg3, arg4, to_candid_variant_n16(this._uploadFile, this._downloadFile, arg5), to_candid_variant_n17(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async deductCoins(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deductCoins(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deductCoins(arg0);
            return result;
        }
    }
    async deleteTrendingTopic(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTrendingTopic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTrendingTopic(arg0);
            return result;
        }
    }
    async fetchTrendingTopicsFromGoogleTrendsApi(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchTrendingTopicsFromGoogleTrendsApi();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchTrendingTopicsFromGoogleTrendsApi();
            return result;
        }
    }
    async fetchTrendingTopicsFromYouTubeApi(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchTrendingTopicsFromYouTubeApi();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchTrendingTopicsFromYouTubeApi();
            return result;
        }
    }
    async filterTrendingTopicsByPlatform(arg0: Platform): Promise<Array<TrendingTopic>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterTrendingTopicsByPlatform(to_candid_Platform_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterTrendingTopicsByPlatform(to_candid_Platform_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateScript(arg0: string, arg1: Variant_hindi_both_english, arg2: bigint, arg3: Variant_dramatic_emotional): Promise<Script> {
        if (this.processError) {
            try {
                const result = await this.actor.generateScript(arg0, to_candid_variant_n14(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_variant_n15(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Script_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateScript(arg0, to_candid_variant_n14(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_variant_n15(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Script_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAccountByPrincipal(arg0: Principal): Promise<UserAccount | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccountByPrincipal(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccountByPrincipal(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerVideoProjects(): Promise<Array<VideoProject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerVideoProjects();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerVideoProjects();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrendingTopic(arg0: string): Promise<TrendingTopic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingTopic(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingTopic(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrendingTopicsSortedByEngagement(): Promise<Array<TrendingTopic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingTopicsSortedByEngagement();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingTopicsSortedByEngagement();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserAccount(): Promise<UserAccount | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserAccount();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserAccount();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideoProject(arg0: string): Promise<VideoProject | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoProject(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoProject(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n46(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n46(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateTrendingTopic(arg0: string, arg1: Platform, arg2: string, arg3: Array<string>, arg4: Array<string>, arg5: EngagementMetrics): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTrendingTopic(arg0, to_candid_Platform_n10(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTrendingTopic(arg0, to_candid_Platform_n10(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateVideoProject(arg0: string, arg1: string, arg2: Array<string>, arg3: string, arg4: Variant_female_male, arg5: boolean, arg6: Variant_tiktok_youtubeShorts_instagramReels, arg7: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVideoProject(arg0, arg1, arg2, arg3, to_candid_variant_n16(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_variant_n17(this._uploadFile, this._downloadFile, arg6), arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVideoProject(arg0, arg1, arg2, arg3, to_candid_variant_n16(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_variant_n17(this._uploadFile, this._downloadFile, arg6), arg7);
            return result;
        }
    }
    async updateVideoProjectStatus(arg0: string, arg1: VideoStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVideoProjectStatus(arg0, to_candid_VideoStatus_n50(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVideoProjectStatus(arg0, to_candid_VideoStatus_n50(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async upgradeToPremium(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upgradeToPremium();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upgradeToPremium();
            return result;
        }
    }
}
function from_candid_Platform_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Platform): Platform {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Script_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Script): Script {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionTier_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionTier): SubscriptionTier {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_TrendingTopic_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrendingTopic): TrendingTopic {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserAccount_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserAccount): UserAccount {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_VideoProject_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoProject): VideoProject {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_VideoStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoStatus): VideoStatus {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserAccount]): UserAccount | null {
    return value.length === 0 ? null : from_candid_UserAccount_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TrendingTopic]): TrendingTopic | null {
    return value.length === 0 ? null : from_candid_TrendingTopic_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VideoProject]): VideoProject | null {
    return value.length === 0 ? null : from_candid_VideoProject_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    topic: string;
    hashtags: Array<string>;
    metrics: _EngagementMetrics;
    platform: _Platform;
    keywords: Array<string>;
    timestamp: bigint;
}): {
    id: string;
    topic: string;
    hashtags: Array<string>;
    metrics: EngagementMetrics;
    platform: Platform;
    keywords: Array<string>;
    timestamp: bigint;
} {
    return {
        id: value.id,
        topic: value.topic,
        hashtags: value.hashtags,
        metrics: value.metrics,
        platform: from_candid_Platform_n21(_uploadFile, _downloadFile, value.platform),
        keywords: value.keywords,
        timestamp: value.timestamp
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    duration: bigint;
    hookLine: string;
    language: {
        hindi: null;
    } | {
        both: null;
    } | {
        english: null;
    };
    style: {
        dramatic: null;
    } | {
        emotional: null;
    };
    mainContent: string;
}): {
    duration: bigint;
    hookLine: string;
    language: Variant_hindi_both_english;
    style: Variant_dramatic_emotional;
    mainContent: string;
} {
    return {
        duration: value.duration,
        hookLine: value.hookLine,
        language: from_candid_variant_n25(_uploadFile, _downloadFile, value.language),
        style: from_candid_variant_n26(_uploadFile, _downloadFile, value.style),
        mainContent: value.mainContent
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    created: bigint;
    username: string;
    coins: bigint;
    tier: _SubscriptionTier;
    videoHistory: Array<string>;
}): {
    created: bigint;
    username: string;
    coins: bigint;
    tier: SubscriptionTier;
    videoHistory: Array<string>;
} {
    return {
        created: value.created,
        username: value.username,
        coins: value.coins,
        tier: from_candid_SubscriptionTier_n30(_uploadFile, _downloadFile, value.tier),
        videoHistory: value.videoHistory
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    name: string;
    tier: _SubscriptionTier;
}): {
    username: string;
    name: string;
    tier: SubscriptionTier;
} {
    return {
        username: value.username,
        name: value.name,
        tier: from_candid_SubscriptionTier_n30(_uploadFile, _downloadFile, value.tier)
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _VideoStatus;
    title: string;
    created: bigint;
    voiceover: {
        female: null;
    } | {
        male: null;
    };
    owner: Principal;
    stockVideoIds: Array<string>;
    script: _Script;
    watermark: boolean;
    subtitles: boolean;
    musicId: string;
    topicId: string;
    format: {
        tiktok: null;
    } | {
        youtubeShorts: null;
    } | {
        instagramReels: null;
    };
}): {
    id: string;
    status: VideoStatus;
    title: string;
    created: bigint;
    voiceover: Variant_female_male;
    owner: Principal;
    stockVideoIds: Array<string>;
    script: Script;
    watermark: boolean;
    subtitles: boolean;
    musicId: string;
    topicId: string;
    format: Variant_tiktok_youtubeShorts_instagramReels;
} {
    return {
        id: value.id,
        status: from_candid_VideoStatus_n40(_uploadFile, _downloadFile, value.status),
        title: value.title,
        created: value.created,
        voiceover: from_candid_variant_n42(_uploadFile, _downloadFile, value.voiceover),
        owner: value.owner,
        stockVideoIds: value.stockVideoIds,
        script: from_candid_Script_n23(_uploadFile, _downloadFile, value.script),
        watermark: value.watermark,
        subtitles: value.subtitles,
        musicId: value.musicId,
        topicId: value.topicId,
        format: from_candid_variant_n43(_uploadFile, _downloadFile, value.format)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    x: null;
} | {
    instagram: null;
} | {
    googleTrends: null;
} | {
    youtube: null;
}): Platform {
    return "x" in value ? Platform.x : "instagram" in value ? Platform.instagram : "googleTrends" in value ? Platform.googleTrends : "youtube" in value ? Platform.youtube : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hindi: null;
} | {
    both: null;
} | {
    english: null;
}): Variant_hindi_both_english {
    return "hindi" in value ? Variant_hindi_both_english.hindi : "both" in value ? Variant_hindi_both_english.both : "english" in value ? Variant_hindi_both_english.english : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dramatic: null;
} | {
    emotional: null;
}): Variant_dramatic_emotional {
    return "dramatic" in value ? Variant_dramatic_emotional.dramatic : "emotional" in value ? Variant_dramatic_emotional.emotional : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    premium: null;
} | {
    free: null;
}): SubscriptionTier {
    return "premium" in value ? SubscriptionTier.premium : "free" in value ? SubscriptionTier.free : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: null;
} | {
    rendering: null;
} | {
    draft: null;
}): VideoStatus {
    return "completed" in value ? VideoStatus.completed : "rendering" in value ? VideoStatus.rendering : "draft" in value ? VideoStatus.draft : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    female: null;
} | {
    male: null;
}): Variant_female_male {
    return "female" in value ? Variant_female_male.female : "male" in value ? Variant_female_male.male : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tiktok: null;
} | {
    youtubeShorts: null;
} | {
    instagramReels: null;
}): Variant_tiktok_youtubeShorts_instagramReels {
    return "tiktok" in value ? Variant_tiktok_youtubeShorts_instagramReels.tiktok : "youtubeShorts" in value ? Variant_tiktok_youtubeShorts_instagramReels.youtubeShorts : "instagramReels" in value ? Variant_tiktok_youtubeShorts_instagramReels.instagramReels : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TrendingTopic>): Array<TrendingTopic> {
    return value.map((x)=>from_candid_TrendingTopic_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VideoProject>): Array<VideoProject> {
    return value.map((x)=>from_candid_VideoProject_n38(_uploadFile, _downloadFile, x));
}
function to_candid_Platform_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Platform): _Platform {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Script_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Script): _Script {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionTier_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionTier): _SubscriptionTier {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n47(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_VideoStatus_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VideoStatus): _VideoStatus {
    return to_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    duration: bigint;
    hookLine: string;
    language: Variant_hindi_both_english;
    style: Variant_dramatic_emotional;
    mainContent: string;
}): {
    duration: bigint;
    hookLine: string;
    language: {
        hindi: null;
    } | {
        both: null;
    } | {
        english: null;
    };
    style: {
        dramatic: null;
    } | {
        emotional: null;
    };
    mainContent: string;
} {
    return {
        duration: value.duration,
        hookLine: value.hookLine,
        language: to_candid_variant_n14(_uploadFile, _downloadFile, value.language),
        style: to_candid_variant_n15(_uploadFile, _downloadFile, value.style),
        mainContent: value.mainContent
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    name: string;
    tier: SubscriptionTier;
}): {
    username: string;
    name: string;
    tier: _SubscriptionTier;
} {
    return {
        username: value.username,
        name: value.name,
        tier: to_candid_SubscriptionTier_n48(_uploadFile, _downloadFile, value.tier)
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Platform): {
    x: null;
} | {
    instagram: null;
} | {
    googleTrends: null;
} | {
    youtube: null;
} {
    return value == Platform.x ? {
        x: null
    } : value == Platform.instagram ? {
        instagram: null
    } : value == Platform.googleTrends ? {
        googleTrends: null
    } : value == Platform.youtube ? {
        youtube: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_hindi_both_english): {
    hindi: null;
} | {
    both: null;
} | {
    english: null;
} {
    return value == Variant_hindi_both_english.hindi ? {
        hindi: null
    } : value == Variant_hindi_both_english.both ? {
        both: null
    } : value == Variant_hindi_both_english.english ? {
        english: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_dramatic_emotional): {
    dramatic: null;
} | {
    emotional: null;
} {
    return value == Variant_dramatic_emotional.dramatic ? {
        dramatic: null
    } : value == Variant_dramatic_emotional.emotional ? {
        emotional: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_female_male): {
    female: null;
} | {
    male: null;
} {
    return value == Variant_female_male.female ? {
        female: null
    } : value == Variant_female_male.male ? {
        male: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_tiktok_youtubeShorts_instagramReels): {
    tiktok: null;
} | {
    youtubeShorts: null;
} | {
    instagramReels: null;
} {
    return value == Variant_tiktok_youtubeShorts_instagramReels.tiktok ? {
        tiktok: null
    } : value == Variant_tiktok_youtubeShorts_instagramReels.youtubeShorts ? {
        youtubeShorts: null
    } : value == Variant_tiktok_youtubeShorts_instagramReels.instagramReels ? {
        instagramReels: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionTier): {
    premium: null;
} | {
    free: null;
} {
    return value == SubscriptionTier.premium ? {
        premium: null
    } : value == SubscriptionTier.free ? {
        free: null
    } : value;
}
function to_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VideoStatus): {
    completed: null;
} | {
    rendering: null;
} | {
    draft: null;
} {
    return value == VideoStatus.completed ? {
        completed: null
    } : value == VideoStatus.rendering ? {
        rendering: null
    } : value == VideoStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
